# Pandas 
```
pip install pandas 
pip install --upgrade pandas
```
- Pandas Series
- Pandas DataFrame --> use various ways to initialize it(dtype,columns,index)
- shape
- head
- tail
- convert to numpy array --> values
- columns
- to_csv (index = false)
- read_csv
-  drop(columns=[])
-  describe()
-  info()
-  iloc
-  loc
-  Access Particular Columns
-  indexing and slicing --> multirow and col
-  columns.get_loc
-  Fancy indexing
-  Filtering
-  unique
-  sort_values(by,ascending)
-  getdummies 
- groupby --> column name, various functions on grp, iterate
- pivot --> summarize and aggregate data,Grouper
- concat--> give as list, ignore_index,join
- merge--> on,how
- dropna
- fillna
- interpolate
- pip install matplotlib

In [7]:
import pandas as pd
import numpy as np

In [48]:
print(pd.__version__)
pd.DF = pd.DataFrame

2.2.3


In [9]:
l1 = np.array([10,20,30,40,50])

In [25]:
pds = pd.Series(l1,index=['A','B','C','D','Fa'],dtype='f8')

In [26]:
pds

A     10.0
B     20.0
C     30.0
D     40.0
Fa    50.0
dtype: float64

In [27]:
type(pds)

pandas.core.series.Series

In [28]:
pds['A']

np.float64(10.0)

In [38]:
marks = {
    'Phy': np.random.randint(1,101,size=5),
    'Chem': np.random.randint(1,101,size=5),
    'Maths':np.random.randint(1,101,size=5)
}

In [39]:
marks

{'Phy': array([74, 70, 63, 98, 72], dtype=int32),
 'Chem': array([41,  9, 37, 56, 48], dtype=int32),
 'Maths': array([65,  9, 38, 56, 34], dtype=int32)}

In [40]:
df = pd.DataFrame(marks,index=['A','B','C','D','E'])

In [41]:
df

Phy  Chem  Maths
A   74    41     65
B   70     9      9
C   63    37     38
D   98    56     56
E   72    48     34

In [42]:
na = np.arange(30).reshape((10,3))

In [49]:
df2 = pd.DF(na,columns=['Physics','Chemistry','Mathematics'])

In [50]:
df2

Physics  Chemistry  Mathematics
0        0          1            2
1        3          4            5
2        6          7            8
3        9         10           11
4       12         13           14
5       15         16           17
6       18         19           20
7       21         22           23
8       24         25           26
9       27         28           29

In [51]:
df

Phy  Chem  Maths
A   74    41     65
B   70     9      9
C   63    37     38
D   98    56     56
E   72    48     34

In [52]:
df.shape

(5, 3)

In [55]:
df2.head(3)

Physics  Chemistry  Mathematics
0        0          1            2
1        3          4            5
2        6          7            8

In [57]:
df2.tail(3)

Physics  Chemistry  Mathematics
7       21         22           23
8       24         25           26
9       27         28           29

In [58]:
df.values

array([[74, 41, 65],
       [70,  9,  9],
       [63, 37, 38],
       [98, 56, 56],
       [72, 48, 34]], dtype=int32)

In [59]:
df.columns

Index(['Phy', 'Chem', 'Maths'], dtype='object')

In [61]:
df2.columns[0]

'Physics'

In [62]:
df

Phy  Chem  Maths
A   74    41     65
B   70     9      9
C   63    37     38
D   98    56     56
E   72    48     34

In [63]:
df.to_csv("Marks.csv")

In [66]:
ndf = pd.read_csv("Marks.csv",index_col='Unnamed: 0')

In [67]:
ndf

Phy  Chem  Maths
A   74    41     65
B   70     9      9
C   63    37     38
D   98    56     56
E   72    48     34

In [73]:
df.to_csv("Marks.csv",sep='|',index=False)

In [74]:
ndf = pd.read_csv("Marks.csv",sep='|')
ndf

Phy  Chem  Maths
0   74    41     65
1   70     9      9
2   63    37     38
3   98    56     56
4   72    48     34

In [75]:
ndf.index = ['A','B','C','D','E']

In [76]:
ndf

Phy  Chem  Maths
A   74    41     65
B   70     9      9
C   63    37     38
D   98    56     56
E   72    48     34

In [77]:
df

Phy  Chem  Maths
A   74    41     65
B   70     9      9
C   63    37     38
D   98    56     56
E   72    48     34

In [82]:
df.drop(['C'],axis = 0,inplace=True)

In [83]:
df

Phy  Chem  Maths
A   74    41     65
B   70     9      9
D   98    56     56
E   72    48     34

In [84]:
df2

Physics  Chemistry  Mathematics
0        0          1            2
1        3          4            5
2        6          7            8
3        9         10           11
4       12         13           14
5       15         16           17
6       18         19           20
7       21         22           23
8       24         25           26
9       27         28           29

In [85]:
df2.describe()

Physics  Chemistry  Mathematics
count  10.000000  10.000000    10.000000
mean   13.500000  14.500000    15.500000
std     9.082951   9.082951     9.082951
min     0.000000   1.000000     2.000000
25%     6.750000   7.750000     8.750000
50%    13.500000  14.500000    15.500000
75%    20.250000  21.250000    22.250000
max    27.000000  28.000000    29.000000

In [86]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Physics      10 non-null     int64
 1   Chemistry    10 non-null     int64
 2   Mathematics  10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes


In [93]:
df[['Maths','Phy']]

Maths  Phy
A     65   74
B      9   70
D     56   98
E     34   72

In [96]:
df.loc[['A','B','E'],['Phy','Maths']]

Phy  Maths
A   74     65
B   70      9
E   72     34

In [98]:
df.loc['A']['Phy']

np.int32(74)

In [100]:
df.iloc[[1,0,3],[2,0]]

Maths  Phy
B      9   70
A     65   74
E     34   72

In [101]:
df.iloc[1:3,1:2]

Chem
B     9
D    56

In [102]:
df.loc['A':'D']

Phy  Chem  Maths
A   74    41     65
B   70     9      9
D   98    56     56

In [103]:
df.iloc[[True,False,False,True]]

Phy  Chem  Maths
A   74    41     65
E   72    48     34

In [109]:
df[df['Phy'] >= 73]

Phy  Chem  Maths
A   74    41     65
D   98    56     56

In [112]:
df.columns.get_loc('Maths')

2

In [113]:
df

Phy  Chem  Maths
A   74    41     65
B   70     9      9
D   98    56     56
E   72    48     34

In [114]:
df['Phy'].unique()

array([74, 70, 98, 72], dtype=int32)

In [115]:
a = np.array([1,3,1,2,4,1,3,2,4,1,2,3,1,4])

In [117]:
np.unique(a,return_counts=True)

(array([1, 2, 3, 4]), array([5, 3, 3, 3]))