# Numpy
```
pip install numpy
```

- Mathematical Calculations
- Numpy Array Creation
- Shape
- indexing
- data types: b,i,u,f,c,m,M,O,S,u,V (https://numpy.org/doc/1.25/reference/arrays.dtypes.html#arrays-dtypes)
- more creation methods: arange, linspace, ones, zeros, eye, diag
- random numbers: Numpy Random Module
    - rand: Random values in given shape
    - randn: Return samples from the Standard normal distribution
    - randint: Return random integer from low(inclusive) to high(exclusive)
    - random: Return random floats in [0.0,1.0)
    - choice: Generates a random sample from given 1D array
    - Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()
- reshape: -1 for unknown
- slicing and assignment
- copy and view: share_memory
- operators(Element wise operations)
- and: &, or: |, not: ~
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing
- Basic reductions: sum, min, max, any, all,argmax, argmin
- Some More Numpy Functions - Statistics: mean, median, average, variance, standard deviation
- iteration: nditer, ndenumerate
- Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
- split: array_split, hsplit
- sort: np.sort
- Broadcasting
- Input from Text File
- Questions

In [5]:
import numpy as np

In [6]:
l1 = [1,2,3,4,5]
l2 = [[1,2,3],[4,5,6]]
l3 = [[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]],[[100,200,300],[400,500,600]]]

In [7]:
print(l3)

[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]], [[100, 200, 300], [400, 500, 600]]]


In [8]:
n1 = np.array(l1)
n2 = np.array(l2)
n3 = np.array(l3)

In [9]:
n1

array([1, 2, 3, 4, 5])

In [10]:
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
n3

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[ 10,  20,  30],
        [ 40,  50,  60]],

       [[100, 200, 300],
        [400, 500, 600]]])

In [12]:
n1.shape

(5,)

In [13]:
n2.shape

(2, 3)

In [14]:
n3.shape

(3, 2, 3)

In [17]:
n3.ndim

3

In [22]:
l3[1]

[[10, 20, 30], [40, 50, 60]]

In [24]:
n3[-1]

array([[100, 200, 300],
       [400, 500, 600]])

In [25]:
n3.dtype

dtype('int64')

In [29]:
# n3 = np.array(l3,dtype = 'float32')
# n3 = np.array(l3,dtype = 'f4')
n3 = np.array(l3,dtype = 'i8')
n3

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[ 10,  20,  30],
        [ 40,  50,  60]],

       [[100, 200, 300],
        [400, 500, 600]]])

In [30]:
n3.dtype

dtype('int64')

In [35]:
l = [[1,2,3],[4,5]]
a = np.array(l,dtype='object')
a

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [36]:
a.shape

(2,)

In [38]:
a[0][1] = 20

In [39]:
a

array([list([1, 20, 3]), list([4, 5])], dtype=object)

more creation methods: arange, linspace, ones, zeros, eye, diag

In [43]:
np.arange(20,dtype = 'f')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.], dtype=float32)

In [44]:
type(n1)

numpy.ndarray

In [47]:
np.linspace(1,2,4)

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [52]:
shape = [2,3,2]
np.ones(shape,dtype = 'i')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [54]:
np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [58]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

- random numbers: Numpy Random Module
    - rand: Random values in given shape
    - randn: Return samples from the Standard normal distribution
    - randint: Return random integer from low(inclusive) to high(exclusive)
    - random: Return random floats in [0.0,1.0)
    - choice: Generates a random sample from given 1D array
    - Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()

In [68]:
(20-10)*np.random.rand(3,2,3)+10

array([[[19.35497596, 16.48014237, 15.43176934],
        [10.97928393, 16.4947988 , 18.97051379]],

       [[15.66281029, 19.8285114 , 19.56268798],
        [19.81045664, 15.80391864, 17.38526294]],

       [[16.10442794, 15.52456964, 10.0619952 ],
        [10.66613801, 12.39750016, 14.6053946 ]]])

In [61]:
np.random.random((2,3))

array([[0.95003176, 0.25107383, 0.0409758 ],
       [0.51358872, 0.35469724, 0.05338177]])

In [63]:
np.random.randn(3,2,3)

array([[[ 1.1948109 ,  1.55353943, -1.32155459],
        [-0.61929736, -0.27946715,  0.72700764]],

       [[ 0.84076246, -0.96739736, -0.57841298],
        [ 0.64711411,  1.68762785,  0.56226468]],

       [[-0.23143343,  0.17896894,  0.20056809],
        [-0.00389362, -1.06736444,  0.59807537]]])

In [67]:
np.random.randint(10,20,size=(2,3))

array([[17, 19, 13],
       [13, 12, 14]], dtype=int32)

In [74]:
np.random.choice(np.arange(10,21),size=(3,2),p = [0.5,0.1,0,0,0,0,0.2,0.2,0,0,0])

array([[17, 10],
       [10, 10],
       [16, 16]])

In [93]:
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [94]:
np.random.seed(1)
np.random.shuffle(a)
a

array([12, 13, 14, 19, 11, 16, 10, 17, 20, 18, 15])

In [99]:
a = np.arange(10,22)

In [100]:
a.shape

(12,)

In [101]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [106]:
b = a.reshape((2,-1,2))

In [107]:
b

array([[[10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21]]])

In [110]:
b.reshape(-1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [113]:
a = np.arange(100).reshape((10,10))

In [122]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [123]:
a[3:7,2:7]

array([[32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46],
       [52, 53, 54, 55, 56],
       [62, 63, 64, 65, 66]])

In [120]:
a[:,2:9:2]

array([[ 2,  4,  6,  8],
       [12, 14, 16, 18],
       [22, 24, 26, 28],
       [32, 34, 36, 38],
       [42, 44, 46, 48],
       [52, 54, 56, 58],
       [62, 64, 66, 68],
       [72, 74, 76, 78],
       [82, 84, 86, 88],
       [92, 94, 96, 98]])

In [124]:
b = a[3:7]

In [127]:
b[0] = np.arange(1000,1010)

In [128]:
b

array([[1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69]])

In [129]:
a

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

In [130]:
np.shares_memory(a,b)

True

In [131]:
c = a[3:7].copy()

In [134]:
c[0] = np.arange(100,110)

In [135]:
c

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69]])

In [136]:
a

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])

In [137]:
np.shares_memory(a,c)

False

In [144]:
a[3:6,2:4] = np.arange(200,206).reshape((3,2))

In [142]:
a

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [1000, 1001,  200,  201, 1004, 1005, 1006, 1007, 1008, 1009],
       [  40,   41,  202,  203,   44,   45,   46,   47,   48,   49],
       [  50,   51,  204,  205,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])